package com.app.barbar.entities;

public enum EnumBeer{
    BRAHMA, ANTARTICA, HEINEKEN, STELLA, SKOL, BUDWEISER, CORONA, GOOSE, TERESOPOLIS, PATAGONIA, IMPERIO, DEVASSA, BOHEMIA,
    POLAR, ITAIPAVA, COLORADO, SPATTEN, CARACU, KILLMES
}
